name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"   # every day at midnight
  workflow_dispatch:       # allows manual run

jobs:
  generate:
    runs-on: ubuntu-latest

    permissions:
      contents: write      # ðŸ‘ˆ needed to push to output branch

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate Snake SVGs
        uses: Platane/snk@v3
        with:
          github_user_name: "Sithmisasanka"
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Push snake to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
